_commit: v1.8.2
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: 'app: rsync-seedbox'
name: rsync-seedbox
namespace: rsync-seedbox
pvc: false
reloader: false
resources:
- configmaps.yaml
- cronjobs.yaml
- external-secrets.yaml
service: false
serviceAccount: false
upstreamURL: ''
url: https://github.com/charlesthomas/homelab-rsync-seedbox
