---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsync-seedbox

commonLabels:
  app: rsync-seedbox

resources:
- argocd-application.yaml
- configmaps.yaml
- cronjobs.yaml
- external-secrets.yaml
- namespaces.yaml
