---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsync-seedbox

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-rsync-seedbox
commonLabels:
  app: rsync-seedbox

resources:
- resources/configmaps.yaml
- resources/cronjobs.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
