---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh
  namespace: rsync-seedbox
spec:
  target:
    name: ssh
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config: |-
          {{ .config }}
        id_rsa: |-
          {{ .key }}
        known_hosts: |-
          {{ .hosts }}
  data:
    - secretKey: config
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: seedbox-ssh-config
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: seedbox-id_rsa
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
    - secretKey: hosts
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: seedbox-known-hosts
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
